### ISSUE TITLE
Using the Await/Async example, give an this error:

### ISSUE THREAD

**Issue by EkamAujla** [HarutoHiroki/alexflipnote.js#4]
UnhandledPromiseRejectionWarning: TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.
at Function.resolveFile (/app/node_modules/discord.js/src/util/DataResolver.js:109:11)
at Function.resolveFile (/app/node_modules/discord.js/src/structures/APIMessage.js:292:41)
at /app/node_modules/discord.js/src/structures/APIMessage.js:224:72
at Array.map (<anonymous>)
at APIMessage.resolveFiles (/app/node_modules/discord.js/src/structures/APIMessage.js:224:46)
at TextChannel.send (/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:46)
at Object.exports.run (/app/src/commands/FunCommands/achievement.js:13:29)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by HarutoHiroki** [comment]
code?

**Comment by HarutoHiroki** [comment]
Tested the code just now, works fine. What's your code, posting only the error won't help

**Comment by EkamAujla** [comment]
This is it :
```const Discord = module.require("discord.js");
const config = require("../../config")
const client = require('alexflipnote.js');
const alexclient = new client(config.FLIPNOTE_TOKEN);

exports.run = async(Silky, message, args) => {
        try{
            let text = args.join(" ");
            if (!text) {
                return Silky.Usage(exports.help.name);
            }
            let link = await alexclient.image.achievement(text);
            message.channel.send({files: [{ attachment: link.file , name: 'file.jpg'}]})
        } catch (err) {
            
                Silky.ReportError(exports.help.name, err)
                
              }
        }
        exports.help = {
            name        : "achievement",
            description : "Turn Text To A MINECRAFT Achievement",
            aliases     : [],
            category    : "Image",
            usage       : "achievement <Text>",
        }
          
        exports.config = {
            botperms    : [`VIEW_CHANNEL`,`SEND_MESSAGES`,`EMBED_LINKS`,`ATTACH_FILES`],
            userperms   : [],
            chnlperms   : [`VIEW_CHANNEL`,`SEND_MESSAGES`,`EMBED_LINKS`,`ATTACH_FILES`],
            premium     : "No",
            enabled     : "Yes",
            guildOnly   : "Yes",
            permLevel   : "User"
        }
```

**Comment by HarutoHiroki** [comment]
well duh that will cause a problem, please read the documentations more carefully specifically line 5-8 after the params table
