### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by GulliDev** [HarutoHiroki/alexflipnote.js#5]
Hi
    "alexflipnote.js": "^1.2.8",

(node:9360) UnhandledPromiseRejectionWarning: Request failed. Status code: 400
(node:9360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by HarutoHiroki** [comment]
Update to latest version and read the docs
